### ISSUE TITLE
First Item of each section, having different height , How to solve it?

### ISSUE THREAD

**Issue by desis123** [jsoendermann/rn-section-list-get-item-layout#15]
First of all thanks for this nice library to make life a lot easier. I have a question, In my section, First row item of each section has different height than other items . I am kind of puzzled to solve that issue. Any help will be greatly appreciated. Thansk in advance.

**Comment by jsoendermann** [comment]
Hi. getItemHeight is given the row index as its third parameter. Something like  `getItemHeight: (rowData, sectionIndex, rowIndex) => rowIndex === 0 ? 100 : 50` should work.

**Comment by desis123** [comment]
@jsoendermann Thanks for quick reply.. I will try now.. and let you know ...

**Comment by desis123** [comment]
@jsoendermann  Seems like everything is working perfectly ...
