### ISSUE TITLE
When I drag to the bottom，I got a error ， “TypeError: right-hand side of 'instanceof' is not callable ”

### ISSUE THREAD

**Issue by huapeng222** [jsoendermann/rn-section-list-get-item-layout#17]
rn 0.62

**Comment by huapeng222** [comment]
![image](https://user-images.githubusercontent.com/7056869/88631529-e4ebc900-d0e4-11ea-8c84-a860833aae56.png)

**Comment by jsoendermann** [comment]
Hi, that doesn't look to me like it's related to this package. Can you share a repro?

**Comment by huapeng222** [comment]
> Hi, that doesn't look to me like it's related to this package. Can you share a repro?

I've found out why， Because I used react-native-swipe-list-view。
