### ISSUE TITLE
Using TypeScript: 'rowData' and 'rowIndex' is declared but never used.

### ISSUE THREAD

**Issue by stabenfeldt** [jsoendermann/rn-section-list-get-item-layout#7]
This is more an TypeScript issue than an "rn-section-list-get-item-layout" issue.
But I'm posting it here anyway as users of "rn-section-list-get-item-layout" might also be using TS. :-)

------------------------

The TypeScript compiler complains about this line:
`getItemHeight: (rowData, sectionIndex, rowIndex) => sectionIndex === 0 ? 100 : 50,` 

```bash
error TS6133: 'rowData' is declared but never used.
error TS6133: 'rowIndex' is declared but never used.
```

I guess both `rowData` and `rowIndex` are used internally in the npm package. But how do I tell that to TypeScript?

**Comment by jsoendermann** [comment]
Hi @stabenfeldt I can't reproduce this error. If you make a small repo that causes this, I can take a look at it.

**Comment by stabenfeldt** [comment]
The error has disappeared. Not sure what made it go away, but I'll definitely make a small repo you can look at if it reappears. Thanks! :-)
