### ISSUE TITLE
getItemHeight is called excessively

### ISSUE THREAD

**Issue by amsul** [jsoendermann/rn-section-list-get-item-layout#8]
Hi @jsoendermann! Thanks for building this helper.

I'm curious why `getItemHeight` is called so often. If I put a `console.count`, it clearly shows that all items in the list are measured **multiple times** whenever a new item is appended.

Is this just the way VirtualizedLists work in React Native?

**Comment by jsoendermann** [comment]
Yes, I believe that's a VirtualizedList issue
